version: 2.1

only-run-on-branches: &only-run-on-branches
  branches:
    ignore:
      - main

only-run-on-main: &only-run-on-main
  branches:
    only:
      - main

node-image: &node-image
  image: circleci/node:14.8.0
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_ACCESS_TOKEN

workflows:
  version: 2
  workflow:
    jobs:
      - publish:
          context:
            - npm
            - github
          filters:
            <<: *only-run-on-main

jobs:
  publish:
    docker:
      - <<: *node-image
    steps:
      - checkout
      - run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc'
      - run: npm install
      - run: npm run semantic-release
